/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GraphicDesigner {
    }
}
declare global {
    interface HTMLGraphicDesignerElement extends Components.GraphicDesigner, HTMLStencilElement {
    }
    var HTMLGraphicDesignerElement: {
        prototype: HTMLGraphicDesignerElement;
        new (): HTMLGraphicDesignerElement;
    };
    interface HTMLElementTagNameMap {
        "graphic-designer": HTMLGraphicDesignerElement;
    }
}
declare namespace LocalJSX {
    interface GraphicDesigner {
    }
    interface IntrinsicElements {
        "graphic-designer": GraphicDesigner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "graphic-designer": LocalJSX.GraphicDesigner & JSXBase.HTMLAttributes<HTMLGraphicDesignerElement>;
        }
    }
}
