/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AppEvent, FreeDrawingDto, GraphicDesingConfig, GraphicTextDto, MediaGallery } from "./index";
export { AppEvent, FreeDrawingDto, GraphicDesingConfig, GraphicTextDto, MediaGallery } from "./index";
export namespace Components {
    interface EmojiPicker {
    }
    interface FreeDrawing {
    }
    interface GraphicDesigner {
        "config": GraphicDesingConfig;
        "src": string;
    }
    interface GraphicGallery {
        "mediaGallery": MediaGallery;
    }
    interface GraphicText {
    }
}
export interface EmojiPickerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEmojiPickerElement;
}
export interface FreeDrawingCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFreeDrawingElement;
}
export interface GraphicDesignerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGraphicDesignerElement;
}
export interface GraphicGalleryCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGraphicGalleryElement;
}
export interface GraphicTextCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGraphicTextElement;
}
declare global {
    interface HTMLEmojiPickerElementEventMap {
        "appEvent": AppEvent<any>;
    }
    interface HTMLEmojiPickerElement extends Components.EmojiPicker, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEmojiPickerElementEventMap>(type: K, listener: (this: HTMLEmojiPickerElement, ev: EmojiPickerCustomEvent<HTMLEmojiPickerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEmojiPickerElementEventMap>(type: K, listener: (this: HTMLEmojiPickerElement, ev: EmojiPickerCustomEvent<HTMLEmojiPickerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEmojiPickerElement: {
        prototype: HTMLEmojiPickerElement;
        new (): HTMLEmojiPickerElement;
    };
    interface HTMLFreeDrawingElementEventMap {
        "appEvent": AppEvent<FreeDrawingDto>;
    }
    interface HTMLFreeDrawingElement extends Components.FreeDrawing, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFreeDrawingElementEventMap>(type: K, listener: (this: HTMLFreeDrawingElement, ev: FreeDrawingCustomEvent<HTMLFreeDrawingElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFreeDrawingElementEventMap>(type: K, listener: (this: HTMLFreeDrawingElement, ev: FreeDrawingCustomEvent<HTMLFreeDrawingElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFreeDrawingElement: {
        prototype: HTMLFreeDrawingElement;
        new (): HTMLFreeDrawingElement;
    };
    interface HTMLGraphicDesignerElementEventMap {
        "appEvent": AppEvent<any>;
    }
    interface HTMLGraphicDesignerElement extends Components.GraphicDesigner, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGraphicDesignerElementEventMap>(type: K, listener: (this: HTMLGraphicDesignerElement, ev: GraphicDesignerCustomEvent<HTMLGraphicDesignerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGraphicDesignerElementEventMap>(type: K, listener: (this: HTMLGraphicDesignerElement, ev: GraphicDesignerCustomEvent<HTMLGraphicDesignerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGraphicDesignerElement: {
        prototype: HTMLGraphicDesignerElement;
        new (): HTMLGraphicDesignerElement;
    };
    interface HTMLGraphicGalleryElementEventMap {
        "appEvent": AppEvent<any>;
    }
    interface HTMLGraphicGalleryElement extends Components.GraphicGallery, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGraphicGalleryElementEventMap>(type: K, listener: (this: HTMLGraphicGalleryElement, ev: GraphicGalleryCustomEvent<HTMLGraphicGalleryElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGraphicGalleryElementEventMap>(type: K, listener: (this: HTMLGraphicGalleryElement, ev: GraphicGalleryCustomEvent<HTMLGraphicGalleryElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGraphicGalleryElement: {
        prototype: HTMLGraphicGalleryElement;
        new (): HTMLGraphicGalleryElement;
    };
    interface HTMLGraphicTextElementEventMap {
        "appEvent": AppEvent<GraphicTextDto>;
    }
    interface HTMLGraphicTextElement extends Components.GraphicText, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGraphicTextElementEventMap>(type: K, listener: (this: HTMLGraphicTextElement, ev: GraphicTextCustomEvent<HTMLGraphicTextElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGraphicTextElementEventMap>(type: K, listener: (this: HTMLGraphicTextElement, ev: GraphicTextCustomEvent<HTMLGraphicTextElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGraphicTextElement: {
        prototype: HTMLGraphicTextElement;
        new (): HTMLGraphicTextElement;
    };
    interface HTMLElementTagNameMap {
        "emoji-picker": HTMLEmojiPickerElement;
        "free-drawing": HTMLFreeDrawingElement;
        "graphic-designer": HTMLGraphicDesignerElement;
        "graphic-gallery": HTMLGraphicGalleryElement;
        "graphic-text": HTMLGraphicTextElement;
    }
}
declare namespace LocalJSX {
    interface EmojiPicker {
        "onAppEvent"?: (event: EmojiPickerCustomEvent<AppEvent<any>>) => void;
    }
    interface FreeDrawing {
        "onAppEvent"?: (event: FreeDrawingCustomEvent<AppEvent<FreeDrawingDto>>) => void;
    }
    interface GraphicDesigner {
        "config"?: GraphicDesingConfig;
        "onAppEvent"?: (event: GraphicDesignerCustomEvent<AppEvent<any>>) => void;
        "src"?: string;
    }
    interface GraphicGallery {
        "mediaGallery"?: MediaGallery;
        "onAppEvent"?: (event: GraphicGalleryCustomEvent<AppEvent<any>>) => void;
    }
    interface GraphicText {
        "onAppEvent"?: (event: GraphicTextCustomEvent<AppEvent<GraphicTextDto>>) => void;
    }
    interface IntrinsicElements {
        "emoji-picker": EmojiPicker;
        "free-drawing": FreeDrawing;
        "graphic-designer": GraphicDesigner;
        "graphic-gallery": GraphicGallery;
        "graphic-text": GraphicText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "emoji-picker": LocalJSX.EmojiPicker & JSXBase.HTMLAttributes<HTMLEmojiPickerElement>;
            "free-drawing": LocalJSX.FreeDrawing & JSXBase.HTMLAttributes<HTMLFreeDrawingElement>;
            "graphic-designer": LocalJSX.GraphicDesigner & JSXBase.HTMLAttributes<HTMLGraphicDesignerElement>;
            "graphic-gallery": LocalJSX.GraphicGallery & JSXBase.HTMLAttributes<HTMLGraphicGalleryElement>;
            "graphic-text": LocalJSX.GraphicText & JSXBase.HTMLAttributes<HTMLGraphicTextElement>;
        }
    }
}
